### ISSUE TITLE
Do we need all four?

### ISSUE THREAD

**Issue by draysonandstock** [Financial-Times/o-visual-effects#17]
We currently have four levels to drop shadows and it might be worth us reducing this to maybe just a high and a low version. We could use the low for things like the header/nav and high for tooltips/pop-ups etc.

I had a bit of look to see where it is being used on .com but beyond header/nav, ad?, tooltip, overlay and now banners. 

Very low priority but worth making a note of as it isn't that clear at the moment which one to use and when.

**Comment by rowanmanning** [comment]
Is this still something you're concerned about, or is it likely to get updated by design? Gonna close for now pending more design direction :)
