### ISSUE TITLE
Not really an issue but could we have an ultra low elevation

### ISSUE THREAD

**Issue by sdbernard** [Financial-Times/o-visual-effects#2]
Something like this...

box-shadow: 0 2px 2px rgba(80,80,80,.12),0 1px 1px rgba(80,80,80,.14)

The others are a little extreme for our uses. Here's an example of where we would use an ultra-low...

![image](https://cloud.githubusercontent.com/assets/2511348/16582244/92668fca-42a5-11e6-9c50-bf171a1eeec6.png)

**Comment by merybenavente** [comment]
@sdbernard we've just added this option, sorry for the delay!
